### ISSUE TITLE
Cypress PoC/migration

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#1102]
Main ticket for Cypress PoC/migration

## Tasks to do

Phase 1a:
- [x] setup cypress
- [x] create basic helpers
- [x] write "Big Happy Path"
- [x] setup CI
- [x] add TS for cypress

Phase 1b (also Marcin):
- [x] create open source project in dashboard (https://www.cypress.io/dashboard/)
- [x] link project in CI

=== these will be new tickets (Bill to create)

E2E migration 1 - to do soon (epic/cypress.mig1)
- migrate smoke/app
- migrate smoke/currency
- migrate smoke/language
- migrate smoke/product-search

E2E migration 2 - to do later (epic/cypress.mig2)
- migrate smoke/login
- migrate smoke/routing
- migrate smoke/terms-and-conditions
- migrate regression/added-to-cart-modal
- migrate regression/address-book
- migrate regression/cart
- migrate regression/payment-methods
- migrate regression/product-details
- migrate regression/register
- migrate regression/productsearch

E2E cypress end game (epic/cypress.last)
- disable protractor tests
- remove protractor tests from CI
- remove protractor tests from repo? (if we will be confident about cypress)

====

## Execution

I would recommend that after Phase 1a/b I would recommend doing a pause. Just to see how tests are working over some period of time and how hard is the maintenance. After some good result, we could proceed with Phase 2-4.

Also, it would be good if more people would work on those tests to learn framework, test debugging and get familiar with our commands/helpers.
