### ISSUE TITLE
Cypress knowledge transfer

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#1247]
- [x] Prepare cypress knowledge transfer session
- [x] Meeting with Europe based team (won't happen - video to watch linked in tribe channel or ask me for link)
- [x] Meeting with Kanada based team
