### ISSUE TITLE
[EPIC MASTER] Forgot Password FR1

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#1260]
- [x] Forgot password page GH-1219
- [x] Reset password page without the backend functionality GH-1220
- [x] Hook up backend functionality in reset password page GH-1412
- [x] Replace JspIncludeComponents with FlexCmsComponents GH-1367
- [x] e2e tests for Forgot password page GH-1295
- [x] e2e tests for Reset Password page GH-1296

**Comment by plabadie** [comment]
PR: #1370

**Comment by plabadie** [comment]
Deployed on dev-com-17 and dev-com-22.

For QA, using dev-com-22 is preferred.

**Comment by KateChuen** [comment]
Tested each ticket individually on dev22. You can find my comments there. 
- Additionally, also tested an expired token (accessed the link and tried to reset the password after 30mins) and received this:
![tokenExpired](https://user-images.githubusercontent.com/45409515/54942705-07287200-4f06-11e9-84a8-8fd99e0c0b57.png)

- Re-used the same link to reset the password a second time within the 30mins and got this:
![sameLinkTwice](https://user-images.githubusercontent.com/45409515/54942714-098acc00-4f06-11e9-85aa-a782e2edac91.png)

- Also checked that we can reset the password to what it was previously
- After resetting the password, we can no longer login with the old password.
- Also reviewed and reran the forgot password & reset password e2e tests, both good.
