### ISSUE TITLE
01 Spike: is ngx-translate library suitable for us

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#1480]
Currently Angular has `i18n` module, but it's main limitation is that it requires separate builds of aplication for every language - which disqualifies it. Situation should improve when new `i18n` Angular's module is released together with the Ivy in the end of 2019.

Because we cannot wait so long, we would like to go for `ngx-translate` library. But firstly we have to evaluate if it has any limitiations that could disqualify it:
- [x] does it work with SSR?
- [x] is [`TranslationService`](https://github.com/ngx-translate/core/blob/master/projects/ngx-translate/core/src/public_api.ts#L42) a singleton to be shared between our lib, shell app, lazy-loaded custom components and industry libraries (e.g. Telco)?
  - known issues with importing `TranslationModule.forRoot()` and `.forChild()`:
    - https://github.com/ngx-translate/core/issues/883
    - https://github.com/ngx-translate/core/issues/912
  - possible workarounds:
    - https://medium.com/@TuiZ/how-to-split-your-i18n-file-per-lazy-loaded-module-with-ngx-translate-3caef57a738f
    - https://medium.com/@miki995/angular-7-ngx-translate-lazy-loaded-modules-36d586b82ba4
    - Maybe we can simply import `TranslationModule.forRoot()` in `@spartacus/core`, but `.forChild()` in other places: in our lib, shell app, and industry libraries - need to check

- [x] does it support pluralization rules OOTB? If not, how we can make it work? Ideas:
    * native [i18nPluralPipe](https://angular.io/api/common/I18nPluralPipe) fixed to work in runtime
    * [ICU expressions compiler for ngx-translate](https://github.com/lephyrus/ngx-translate-messageformat-compiler)

- [ ] If `ngx-translate` happens not to be suitable for us, we will have to think of alternative solutions in #1532

**Comment by Platonn** [comment]
### Results of the spike
#### Limitations
- lazy-loaded translations - we cannot use them in lib
  - only lazy-loaded modules (`loadChildren` routes) can have its own lazy-loaded translations
  - the lazy-loaded module cannot at the same time use its own lazy-loaded translations and reuse shared (already loaded) translations (flag `isolate:boolean`)

#### Dependency
- Having `ngx-translate` as a dependency brings a risk. If it has some bugs that stops us or in some future version of Angular there comes a breaking change that is not compatible with the current `ngx-translate` version, we will have to wait with uprading to new Angular until the compatible release of `ngx-translate` comes.
#### Known bugs in ngx-translate:
- [ngx-translate issue 998](https://github.com/ngx-translate/core/issues) - we can live with it by avoiding the usage of the syntax `<p translate>KEY</p>`. Just use `{{ KEY | translate }}` or `<p translate="KEY"></p>`  instead.

#### Other
- luckily I could not reproduce [issue 833](https://github.com/ngx-translate/core/issues/) with forRoot/forChild 
  - both methods allow providing your own: loader, compiler, parser and missing translations handler
  - I used interchangeably forRoot and forChild in `app.module` and in `storefrontlib` with success. Because of the hierarchy of providers, `app.module` always overwrite providers from `storefrontlib` (regardless of where I used forRoot/forChild)
  - I would suggest such a usage: import forRoot in the lib (to have Spartacus working OOTB) and if Customer wants, he may overwrite loader, etc. by importing forChild in app.module
