### ISSUE TITLE
introduce virtual route for logout

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#1514]
currently logout logic is hardcoded and tightly coupled to the  CMS sample data. This doesn't allow for flexibility and extensibility. 

A common pattern on storefronts is the usage of a page for the logout, some storefronts use a virtual url for this and redirect to the homepage or stay on the currentpage, where other storefronts show a goodbye message. 

In order to support all scenarios, we'll check whether there is a (semantic) login page available. If this is the case, we redirect to this page, otherwise, we stay at the current page.

**Comment by tobi-or-not-tobi** [comment]
QA:
- verify that the logout link uses the /logout route on hover
- verify that by default the logout process keeps you on the current page
- add cms page with pageLabel /logout and verify that this page is shown upon logout

**Comment by KateChuen** [comment]
Tested on dev17 (chrome, safari & firefox).

- [X] verify that the logout link uses the /logout route on hover
- [X] verify that by default the logout process keeps you on the current page
- [X] add cms page with pageLabel /logout and verify that this page is shown upon logout
