### ISSUE TITLE
[EPIC] Account Profile FR1

### ISSUE THREAD

**Issue by plabadie** [SAP/cloud-commerce-spartacus-storefront#1580]
- [x] GH-1575 Update Personal Details
- [x] GH-1576 Update Password
- [x] GH-1577 Update Email
- [x] GH-1578 Consent Management
- [x] GH-1579 Close Account

# Facade Tickets:

## Overview:

- Implement the facade api for the form ( facade functions, Actions, Effects, Reducers, OccService )
- Base the implementation on the proposed Form Processing flow : 
![form-foundation](https://user-images.githubusercontent.com/7065346/53977034-29cd2500-40d6-11e9-9777-fb6f321838ac.png)

- Leverage the generic load state mechanism in spartacus
  https://wiki.hybris.com/display/spar/Load+Once+Feature+Notes

## Facade functions:

The facade must contain these functions:

- {featurteName}()
- get{featurteName}ResultLoading(): Observable\<bool>
- get{featurteName}ResultError(): Observable\<bool> ?
- get{featurteName}ResultSuccess(): Observable\<bool>
- get{featurteName}ResultValue(): Observable\<any? | type?>
- reset{featurteName}ResultState(): void

## Effect

- The effect's purpose is to call the OCCService and dispatch either an error or a success action.
- As a rule of thumb, the value of the action that triggered the effect is added to the success action payload.  This way the reducers can update the store.

## Process State Management

To manage the process state, use the process state feature, see GH-1839

Example implementation for the update user details, see GH-1873

## Actions & Process Management.

- Extend generic entity loader actions to leverage the generic reducers.

## Reducers

- To manage the form process state, we can leverage the generic loader reducer. We don't need to create a reducer for the form processing state.

- _However_, we need to create as many reducers as required to apply a successful update in the store state. For example, an email update success action needs to be picked up by the user reducer to update the user details and also by the authentication reducer to update the userId.

## OCC Calls

See this postman collection for examples: 
[OCC_Account_Profile.postman_collection.json.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/2943188/OCC_Account_Profile.postman_collection.json.zip)

# UI Tickets:

## Account Profile Wireframes

Wireframes for the My Account section are here:
https://98qkkl.axshare.com/#g=1&p=w_account_edit_name

## CMS

- Each form must live in its own CMS page.
- Reuse the existing CMS page if possible.  They should be using the template: `AccountPageTemplate`
- Each form component will be a CMSFlexComponent.  Add them to the slot for the `BodyContent` position.
- Add the link to the page to the "My Account" Navigation menu in this order, between 'Payment Details' and 'Sign Out':

```
- Personal Details
- Password
- Email Address
- Close Account
- Concent Management
```

The links were temporarily remived until we implemeted the features. To add a link to the menu, you must do two things:

One, just remove the appropriate "REMOVE" statements here:
https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/browse/resources/spacceleratorsamplesaddon/import/contentCatalogs/electronicsContentCatalog/cleaning.impex#86,94,102

Two, add the appropriate "NavNode" in the list go the MyAccountNavNode's children, between 'Payment Details' and 'Sign Out':
https://stash.hybris.com/projects/C3PO/repos/spacceleratorsamplesaddon/browse/resources/spacceleratorsamplesaddon/import/contentCatalogs/electronicsContentCatalog/cms-responsive-content.impex#200

## URLs

The account pages should all be created under a "/my-account", like "/my-account/featurename".
The yet to be implemented account home page will be "/my-account" and we want the account features to be under it.

## URL Protection

Use the current mechanism to restrict access to the pages only for authenticated users.
Note, however, that team Framed is working on a generic mechanism to implement this from CMS configs.

## Form validation

- Implement the form behaviour as close as possible to the form behaviour guidelines in the wireframes:
  https://98qkkl.axshare.com/#g=1&p=main_action_on_form_pages
  https://98qkkl.axshare.com/#g=1&p=mandatory_and_optional_form_field
  https://98qkkl.axshare.com/#g=1&p=inline_error_behaviour

Key takeaways are:

- Don't disable form buttons.
- Leave the user a chance to enter a valid value before displaying an error message.
- Support empty abandonment.
- Show all validation messages (if any) when the form is submit.

So far, the way we get the closest to the requirement without adding too much complexity is like this (see the small forgot password form):

```
<div
        class="invalid-feedback"
        *ngIf="
          form.controls['userEmail'].invalid &&
          (submited ||
            (form.controls['userEmail'].touched &&
              form.controls['userEmail'].dirty))
        "
      >
```

## Transitions

- Submit: Display a spinner instead of the form and it's buttons.  Gives feedback that the fomr is processing + helps prevent multiple submits.
- Success: Go to the home page. Display a success message.
- Error: Stay on the page. Let the global error management display the error message.
- Cancel: Go to the home page.

# E2E Tickets

- Account profile e2e tests are considered 'Regression Tests'
- We wish to merge/release the features independently. The Account profile e2e tests should not depend on each other.

Create a new user for these features for sure:

- Update Email
- Update Password
- Close Account
- Update Personal Details

Up to the implemetor to chose to create a user or reuse for :

- Consent Management
