### ISSUE TITLE
[EPIC] Guest checkout FR1

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1608]
This is the epic ticket for guest checkout FR1.

The epic branch is **epic/guestcheckout-fr1**

Best to do this mostly sequentially.
- [x] #1182 1a. Create guest login guard (must do 1A before 1B)
- [x] #1387 1b. Update login form with second options
- [ ] #1179 1c. Create occ call to add email to cart (can be done in parallel with 1A/B)
- [ ] #3784 1.d Add form validation to checkout login (can be done in parallel with 1C)
- [ ] #1180 2. Update shipping address and method components
- [ ] #1181 3. Update payment and summary components
- [ ] #1494 4. E2e tests

Note: until OCC PR RAY-229 is merged [it is, see [RAY-229](https://jira.hybris.com/browse/RAY-229)]
1a/1b: can be done
1c: can be started but not finished
2, 3, 4: can't be done

### Postman collection for guest checkout flow
[Guest checkout collection.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/3457841/guest.checkout.collection.zip)

### Wires:
Sign in: 
1: https://98qkkl.axshare.com/#g=1&p=d_sign_in_member_default
2: https://98qkkl.axshare.com/#g=1&p=d_sign_in_guest_default
Checkout:
1: https://98qkkl.axshare.com/#g=1&p=d_guest_checkout_step1_ship_addy
(no ability to choose a saved address)
2: https://98qkkl.axshare.com/#g=1&p=d_guest_checkout_step2_ship_method
(shipping is the same)
3: https://98qkkl.axshare.com/#g=1&p=d_checkout_step3_payment
(no chance to choose a saved billing address)
4: review is the same

This is FR1. In FR2, we'll add the ability to create an account at confirmation page.

**Comment by Xymmer** [comment]
Louis led the push for creating the Guest Checkout tickets, but the execution will be with Asterix. Louis is available for consultation so any questions, send to him.

**Comment by giancorderoortiz** [comment]
Proposed functionality should follow a SDLC as specified here: https://wiki.wdf.sap.corp/wiki/display/PSSEC/Secure+Software+Development+Lifecycle+Overview

And must comply with security standards as detailed here:
https://wiki.wdf.sap.corp/wiki/display/PSSEC/SAP+Product+Standard+Security+-+Version+8.0
