### ISSUE TITLE
cx-delivery-mode refactor

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#1731]
Main ticket: #1723 

Changes to do (some work in checkout service/store required):

- [x] use goToStep (created in #1729) event instead of selectMode
- [x] remove input and read that directly from the checkout service
- [x] set delivery mode from component instead of the container
- [x] fetch delivery mode only once on init (checkout service should take care of updating)
- [x] add loading state to component
- [x] remove not needed `tabindex=0`
- [x] refresh cart after delivery-mode set (use effect?)
