### ISSUE TITLE
cx-payment-method refactor

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#1732]
Main ticket: #1723 

Changes to do (some work in checkout service/store required):

- [x] use goToStep (created in #1729) event instead addPaymentInfo
- [x] remove input and read directly from checkout service
- [x] set payment method from component instead of the container
- [x] refresh cart after payment-method set (use effect?)
