### ISSUE TITLE
cx-place-order component

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#1734]
Main ticket: #1723 

Changes to do:
- [x] extract terms and conditions checkbox and place order button to separate component
- [x] invoke the placeOrder method from that component
- [x] invoke the event to clear container component and redirect to order confirmation page
