### ISSUE TITLE
Configurable OCC Endpoints [master]

### ISSUE THREAD

**Issue by LTiger14** [SAP/cloud-commerce-spartacus-storefront#1790]
This is the master ticket for making the occ calls dynamic.

Project board: https://github.com/SAP/cloud-commerce-spartacus-storefront/projects/50

**Merge to** `epic/configurableoccendpoints`

The general rules are as follow: **See product occ adapters for example**
- Create a config file in `occ/adapters/`YOUR_MODULE`
- Add endpoints config with the full endpoint that comes after `rest/v2`. Use single quotes with a string template syntax `${variable}`
- In the service import `OccEndpointsService` to build the url from the endpoint key and parameters
- Add endpoint keys to `OccEnpoints` model in `occ-enpoints.model.ts`

### Tickets
- [x] #1791 Auth module
- [x] #1792 Occ Cart adapters
- [x] #1794 Cms module
- [x] #1795 Occ Site-context adapters
- [x] #1796 Occ Store-finder adapters
- [x] #1797 Occ User adapters
- [x]  #3783 Occ Checkout adapters

**Note** this ticket is only to keep track of the tickets.

Work off of an epic branch `epic/configurableoccendpoints`.

**Comment by Xymmer** [comment]
To prevent pollution of development, shouldn't we always merge to an epic branch?

**Comment by LTiger14** [comment]
Yeah actually we can do that so the configs are all released at the same time.

**Comment by LTiger14** [comment]
### For QA:

All tickets must be QAed on dev-19.
See individual tickets in the board.

**Comment by LTiger14** [comment]
### For QA:

To configure an endpoint:
1. In dev-19 make sure that the login is functional
2. Stop server using `./spartacus.sh stop`
3. In the Spartacus install location open `app/storefrontapp/src/app/app.module.ts` 
4. Under `baseUrl` add
```
endpoints: {
   login: 'should_not_work'
}
```
Save
5. Restart the server using `./spartacus.sh start`
6. Try to login -> it should not work and in the network tab you should see a call to the `/should_not_work` endpoint.

**Comment by giancorderoortiz** [comment]
QA comments:
  #1791 Auth module - retest ok. 
  #1792 Occ Cart adapters - pend improvements. 
  #1795 Occ Site-context adapters - test ok
  #1797 Occ User adapters - test ok
  #3783 Occ Checkout/Cart adapters - test ok
