### ISSUE TITLE
Remove subscriptions in multi-step-checkout component

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#2021]
- [x] Remove processSteps method in multi-step-checkout container component.
- [x] Fix loadCart usage in checkout effects. Look into FR2 branch for solution.
- [x] On init invoke loading checkout details with checkout service `loadCheckoutDetails`. Make sure checkout state is restored.
