### ISSUE TITLE
Support array of routes in url pipe - for nested and relative routes

### ISSUE THREAD

**Issue by Platonn** [SAP/cloud-commerce-spartacus-storefront#2057]
- [x] remove need of  `[].concat` for urls to nested routes - `cxTranslateUrl` should handle the array of routes
- [x] move flag `{relative:true}` from route object to the parameters of the pipe
- [x] don't translate parts of url that are not objects (allow for `'../../'` string in route array)
  - [x] add syntactic sugar: allow fro only one object, not wrapped in array
