### ISSUE TITLE
Check unit tests coverage of new created components

### ISSUE THREAD

**Issue by Matejk00** [SAP/cloud-commerce-spartacus-storefront#2311]
Because of Pipeline warnings we need to check unit tests coverage of newly created components in checkout.

- [x] Check coverage of newly created tests
- [x] Improve tests for checkout-config.service
- [x] Verify tests for other newly created componets

**Comment by Pucek9** [comment]
checkout-config.service 62%
