### ISSUE TITLE
Fix bugs found during manual test

### ISSUE THREAD

**Issue by Matejk00** [SAP/cloud-commerce-spartacus-storefront#2534]
- [x] Not logged in user is able to reach directly checkout step pages: f.e. /checkout/payment-details

- [x] When unlogged user add some product to the cart and then click procced to checkout is redirected to first checkout step, but when he will fill shipping address form is not able to go forward (maybe because userId param is missing?)
- [x] On shipping address step "Back to cart" button is not working
- [x] When payment step is not filled yet, user is able to go directly to /checkout/review-order using browser bar.
