### ISSUE TITLE
Doc input required (Asterix) (1 left for Michal)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3785]
The following Asterix tickets still need doc input. 
The tickets were closed and part of 1.0 release so I moved them to Accepted 1907-04 sprint (https://github.com/SAP/cloud-commerce-spartacus-storefront/projects/48).
After reviewing the issue, add a comment here indicating to Matt if there is anything to do.
When all reviewed, assign this ticket to Matt.

- [ ] #124 (Michal G)
- [x] #2663
- [x] #1775 Kris: no docs needed
- [x] #2147 Kris: no docs needed
- [x] #2314 Kris: no docs needed

**Comment by Zeyber** [comment]
#2663: I don't think that any doc input is required. The changes from the resulting PR were only styling-related without intended user-customization.
https://github.com/SAP/cloud-commerce-spartacus-storefront/commit/154e6bcc52b682bdebdf37cc18a14093aded1d17

**Comment by Pucek9** [comment]
https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/pull/256
