### ISSUE TITLE
Check develop for breaking changes; revert if so

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3817]
We accidentally introduced some breaking changes in develop. (Blame: Bill!)
For short term: let's revert anything that's a breaking change, with exception of any blocker bug or critical security risk. Talk to Bill if unsure.

Your task: look for you name, check the commit. If it's a breaking change, revert. Create new ticket labelled "breaking change" and point to old ticket.

Note: If you aren't the owner, please find out who is, pass the ticket on, and update the list.

- [x]  Brian #2737 b439aa434 user redirected to previously viewed account page after logging out (breaking - GH-3839)
- [x]  Brian #3754 9844ceea4 Unstable E2E: regression/my-account/payment-methods.e2e-spec.ts (not breaking)
- [x]  Gil #3708 f12c25406 Bumping versions for 1.0.1 manually since release branch was tailored… (not breaking)
- [x]  Gil #3716 2bfba33b8 fix: Fixing wrong import (not breaking)
- [x]  Gil #3721 85938c298 Removing vscode settings from source control (not breaking)
- [x]  Gil #3744 c13e497fa feat(@spartacus/assets): Adding snapshot build support for assets library (not breaking)
- [x]  Louis #3229 d4c834e5b fix: don't load translations if not initialized - Breaking, resolved in #3837. New ticket #3838 
- [x]  Nik #3560 8e89ffedc feat: add exclusion mechanism for syncing to browser's storage  - not breaking
- [x]  Nik #3662 c8dc7e6e7 Revert "feat: remove kyma refresh token from localStorage (was this reverted?) - not breaking
- [x]  Nik #3742 ca95c516b fix: added rootDir property for ivy  - not breaking
- [x]  Nik #3757 9f90ba0bd fix: handle circular dependencies in error serializer  - not breaking
- [x]  Nik: #3452 9602d10b0 fix: handle complex objects in makeErrorSerializable()  - not breaking
- [ ] Radhep - Re-run e2e tests after changes have been reverted
- [x]  Patrick #3687 99e998a80 fix: Fix issue with billing address in a country that has no regions. - not breaking
- [x]  Radhep #3697 e4dc94961 Fix: Failing E2E: Update Profile
- [x]  Radhep #3699 7e9a31b05 Fix: Failing E2E: language-registration-page.e2e-spec.ts
- [x]  Radhep #3701 fbbd7907a Fix: Failing E2E: language-cart-page.e2e-spec.ts
- [x]  Radhep #3705 bf9f425fc Fix: Failing E2E: mobile/product-search-store-flow-mobile.e2e-spec.ts
- [x]  Radhep #3710 3301a251e Fix: Unstable E2E: Payment-Methods
- [x]  Radhep #3718 d3fea58d0 Fix: Failing E2E: language-my-account-pages.e2e-spec.ts
- [x]  Radhep #3720 45e39b2c1 Fix: Failing E2E: Checkout as Persistent User
- [x]  Radhep #3733 fdb8217c9 Fix: mobile/register-mobile.e2e-spec.ts
- [x]  Radhep #3737 4ae2ffcad Fix: Failing E2E: smoke/login.e2e-spec.ts
- [x]  Radhep #3745 71c42f4f4 Fix: Refactor checkout-flow e2e tests
- [x]  Radhep #3746 4649ee395 Failing E2E: regression/update-email.e2e-spec.ts
- [x]  Radhep #3753 d29746ac3 Unstable E2E: regression/register.e2e-spec.ts
- [x]  Radhep #3779 4e83b814b Failing E2E: regression/register & mobile/register
- [x]  Wei #3696 edfc44f06 feature/GH-3055: change unconsignedEntries status from inProcess to pending - (not breaking)
- [x]  Wei #3748 f17883e32 Feature/gh 3736 - (not breaking)
- [x]  Wei #3732 dc7c97f3d feature/GH-3340: capture internal server error

**Comment by Xymmer** [comment]
Kris added possibility of #3736 (Wei)

**Comment by Platonn** [comment]
@Xymmer , I'll take care of it in https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3831
