### ISSUE TITLE
Check develop for breaking changes; revert if so

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3818]
We accidentally introduced some breaking changes in develop. (Blame: Bill!)
For short term: let's revert anything that's a breaking change, with exception of any blocker bug or critical security risk. Talk to Bill if unsure.

Your task: look for you name, check the commit. If it's a breaking change, revert. Create new ticket labelled "breaking change" and point to old ticket.

Note: If you aren't the owner, please find out who is, pass the ticket on, and update the list.

- [x]  Bernie #3586 57f94c62f fix(@spartacus/core): Extend checkout flow E2E tests with a less expensive product **[Not BC]**
- [x]  Bernie #3703 9d12a1ba9 feat(@spartacus/core): Add cypress as the reference type **[Not BC]**
- [x]  Bernie: #3337 fda8b20c0 fix(@spartacus/storefront): CVV and Card Number Input changes **[BC, ticket: #3826]**
- [x]  Bernie #3659 d2f6f7464 improvement: change for card and cvv number inputs from text to number **[BC, ticket: #3826]**
- [x]  Bernie #3689 f4cc950c4 fix for missing OnlyNumberDirective import **[BC, ticket: #3826]**
- [x]  Mateusz #3057 30b3240ea fix: add filters styling on mobile  **[BC, ticket: #3822]**
- [x]  Mateusz #3582 8668bcbe8 fix: leaking data in store when global message is removed **[Not BC]**
- [x]  Mateusz #3402 3e6045031 fix: Clear form fields before typing new input for certain form in e2e tests. **[Not BC]**
- [x]  Patryk #3655 3cd74fe68 fix: prevent browsers from autofill on user update email form **[Not BC]**
- [x]  Patryk #3657 4f5be2a05 fix: change title native dropdown for application specific **[BC, ticket: #3823]**
- [x]  Patryk #3658 7377c0f47 fix: export for CheckoutConfigService **[Not BC]**
