### ISSUE TITLE
Check develop for breaking changes; revert if so

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3819]
We accidentally introduced some breaking changes in develop. (Blame: Bill!)
For short term: let's revert anything that's a breaking change, with exception of any blocker bug or critical security risk. Talk to Bill if unsure.

Your task: look for you name, check the commit. If it's a breaking change, revert. Create new ticket labelled "breaking change" and point to old ticket.

Note: If you aren't the owner, please find out who is, pass the ticket on, and update the list.

- [x]  Caine #3028 94f5130b9 feat: search box navigation thru results with up/down keys does (YES BREAKING, but will be opt in for 1.0.2)
- [x]  Caine #3467? 4a6b59ec6 fix: add correct focus for 'expiration year' select (YES BREAKING, but tiny change to DOM so ignore)
- [x]  Caine #3497? 598d111e1 Revert "feat: ability to hide pagination when single page is available" (YES BREAKING, but thinking how to fix)
- [x]  Caine #3723 6fe4dcf51 Fix: Compile Error when building SSR (NOT BREAKING)
- [x]  Kris #3643 1d646490f feat: allow for disabling route matcher while still generating semantic URLs (NOT BrEAKING, additive)

**Comment by Zeyber** [comment]
#3723 is not a breaking change

**Comment by Platonn** [comment]
#3643 is an additive, non-breaking change - a new feature helpful in migrating routes from old accelerators

**Comment by Zeyber** [comment]
@developpeurweb Would you consider #3467 to be a breaking change? It consists of a slight modification to the DOM.

**Comment by Xymmer** [comment]
I think Miguel might be on vacation now, let's ignore 3467 since it's tiny.

**Comment by Zeyber** [comment]
#3028 Breaking change fixes PR in code review. Feature will be opt. in.

Breaking changes for future ticket: #3827

**Comment by Zeyber** [comment]
#3497 I would consider NOT to be a breaking change as it introduces a toggle input defaulting to as-before component functionality. The user can choose to add this feature or not.

**Comment by Zeyber** [comment]
#3497 After talking with Stan, there is a breaking change in here that needs to be fixed.

**Comment by Zeyber** [comment]
#3028 Has been reverted.
#3497 Has been fixed for breaking changes.
