### ISSUE TITLE
Spike express checkout

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3874]
Feature description is here: #88

FR1 will focus on creating basic functionality only: 

- [x] Create Express Checkout epic branch #3924
- [x] Add Express checkout config #3919
- [x] Update Checkout configuration with default delivery mode #3923
- [x] Add Express Checkout service #3917
- [x] Add Express checkout guard #3918
- [ ] Ensure to keep correct feature versioning in EC-FR1 #4140
- [ ] Unit tests for express checkout #4054

In FR2 we will allow for override config from the back-office
- [ ] Add Express Checkout configs to back-office #4138
- [ ] Allow for configuration Express Checkout from the backend #4001
- [ ] DOC Express Checkout #4000 

In FR3 we can extend the usability for end-user
- [ ] Add preferred delivery mode setup #3915 (depends on backend #3920)
- [ ] Select delivery mode from default config #3925 (not express checkout, but config can be shared)
- [ ] Update Checkout configuration for skip filled steps (Continue to review) #3922

**Comment by Xymmer** [comment]
closing as everything is represented by tickets
