### ISSUE TITLE
Test Consignment Tracking

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#4126]
Test #3364. -> Do we have an E2E test for it?

- [x] Place an order, go to Order History. On Order Detail Page, check order status is InProcess, therefore there's no "Track Package" button. 

- [x] Wait/Change order status to Completed/Shipped in backend. Go to Order Details Page, check status is Shipped, and there's a "Track Package" button. 

- [x] A Pop-up is opened when you click on the "Track Package" button to show the package tracking information.

- [x] If there is no tracking information yet, show a message to indicate this situation

- [x] Otherwise, show the tracking information:
- Estimated Delivery data
- Delivery Service(a.k.a Delivery Carrier Name)
- Tracking Number(no link for now)
- Package routing(in reverse chronological order). Don't need "Shipped" item in the list; OOTB, show the mock package tracking events

- [x] Show a loading indicator in the pop-up before receiving data from backend server

- [x] Smoke Test on different browsers & devices.

**Comment by KateChuen** [comment]
Tested it locally by deploying their feature branch, and using their OCC endpoint. 

- All the points above were successful. Will just wait for it to be released to test officially test it. 

![Screen Shot 2019-08-22 at 2 27 10 PM](https://user-images.githubusercontent.com/45409515/63541698-a6b95300-c4ec-11e9-9bbd-9e855f3b46b4.png)
![Screen Shot 2019-08-22 at 2 27 18 PM (2)](https://user-images.githubusercontent.com/45409515/63541699-a6b95300-c4ec-11e9-815e-bfcf2dcecf3e.png)
![Screen Shot 2019-08-22 at 2 27 29 PM](https://user-images.githubusercontent.com/45409515/63541700-a6b95300-c4ec-11e9-8d22-606b67d2d0ac.png)

**Comment by KateChuen** [comment]
one tiny thing to check is the mobile breakpoint. Told their QA about it.
So basically, when you open the tracking info, and there's a lot of data, you can scroll in the popup window. But then, you can scroll too much, and see the background. 

![Screen Shot 2019-08-22 at 2 43 45 PM](https://user-images.githubusercontent.com/45409515/63542923-948ce400-c4ef-11e9-88cc-7e22cacfd6cb.png)

**Comment by peterwoetzel** [comment]
Not working again in spa 1.4 with CXCOMM190500P_7
Endpoint is different.
**SPA Request:**
`https://localhost:9002/rest/v2/electronics-spa/orders/00001004/consignments/a00001004/tracking?lang=en&curr=USD`
**Correct Request:**
`https://localhost:9002/rest/v2/electronics-spa/users/current/orders/00001004/consignments/a00001004/tracking?lang=en&curr=USD`
**means**: `/users/<id or current>` is missing
