### ISSUE TITLE
Keyboard Accessibility - Working Doc

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#4136]
_This will be the documentation for Accessibility that can be transfered into official Spartacus docs after the topic is clearly defined and implemented. For now, it is a working document to outline scope._ 

**Accessibility**

[Outline here]

**Keyboarding (label: a11y/keyboard)**

- [ ] Tabbing Navigation (checklist ticket #4142, label: a11y/keyboard/tab-key-nav)
- [ ] Arrow Key Navigation (checklist ticket #4178, label: a11y/keyboard/arrow-key-nav)
- [ ] Check elements with focus provide feedback (checklist ticket #4170, label: a11y/ux/focus

**Comment by Zeyber** [comment]
Closing as related documentation is already written elsewhere.
