### ISSUE TITLE
Create Tickets for Keyboard tab-key navigation through app items

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#4142]
Pressing "tab" navigation through app sections can access all items in sensible order. Write e2e tests ensure this order stays correct going into the future.
- [x] Header (Desktop) #4164
- [x] Header (Mobile) #4167
- [x] Footer #4159 
- [x] Home #4173
- [x] Sign In #4197
- [x] Reset Password #4198
- [x] Register #4199
- Product
	- [x] Product Page #4200 
	- [x] Product List #4201 
	- [x] Add to cart #4202 
- [x] Cart #4203 
- Checkout
	- Shipping Address
		- [x] Choose Shipping Address #4204
		- [x] Add New Address #4205
	- [x] Delivery Mode #4206 
	- Payment Details 
		- [x] Choose Payment Method #4207 
		- [x] Add New Payment #4208 
	- [x] Review Order #4209 
	- [x] Order Confirmation #4210 
- My Account
	- [x] Order History #4212
	- Address Book
		- [x] Addresses #4213
		- [x] Add New Address #4214
		- [x] Edit Address #4215
	- [x] Payment Details #4216
	- [x] Personal Details #4217
	- [x] Change Password #4218
	- [x] Email Address #4219
	- [x] Consent Management #4220
	- [x] Close Account #4221
_Note: Remove pages coming from cms from this list_

**Comment by Zeyber** [comment]
Tickets created
