### ISSUE TITLE
Make user store consistent with other core modules

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#691]
This is a followup ticket to #263 

Some things that should be fixed include:
- [x] Move feature selector out of reducers/index.
- [x] ~~Import SateModule in store module~~ (already done)
- [x] ~~Move selectors from reducers~~ (already done)
- [x] Selectors could use StateWithUser instead of any
- [x] Flatten storefrontlib structure by removing somponents folder

**Comment by marlass** [comment]
Most of the points finished. Created new issue #974 for some duplicate files after flatting user module directory structure.
