### ISSUE TITLE
Improve CMS module in core lib

### ISSUE THREAD

**Issue by dunqan** [SAP/cloud-commerce-spartacus-storefront#839]
- [] Move ComponentMapperService to service folder
- [] Move DefaultPageService to service folder
- [] Rename occ/occ-cms.service.ts to occ/cms.service.ts

**Comment by marlass** [comment]
Seems ok.
