### ISSUE TITLE
Disable cms components for SSR

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#925]
Customers might want to disable CMS components for multiple reasons:
- a CMS component requires personalised input and should not or can not be rendered without it
- a CMS component is not required for SSR output and for performance reason will be removed from the rendering process
- a CMS component interacts with external services (latency) and is not relevant for indexing and social sharing

We like a generic configuration per CMS component to disable cms componnt s in SSR in a generic way:

`disableSSR: true` (defaults to `false`)

**Comment by Platonn** [comment]
### QA steps
#### Disable component for SRR
- [ ] disable some CMS component for SSR, for example searchbox in `search-box.module.ts`:
   ![obraz](https://user-images.githubusercontent.com/4001059/52487846-d0e59c00-2bbe-11e9-9a46-6932fb88901a.png)
   (I've tested searchbox, so you can test using some different components).

#### Verify: Component doesn't render in SSR
- [ ] disable JS in your browser (to see only the initial html rendered by the server)
- [ ] run app in ssr mode:
   ```
   yarn build:core:lib
   yarn build
   yarn build:ssr
   yarn start:ssr
   ```
- [ ] open `http://localhost:4200/` and verify that searchbox component wasn't rendered
*Note:* app in SSR has Japan site context, it's normal

#### Verify: Component renders in non-SSR
- [ ] re-enable JS in your browser and refresh page (to see also the app re-rendered by JS)
- [ ] refresh `http://localhost:4200/` and verify that searchbox component was rendered

**Comment by Platonn** [comment]
QA steps in the some comment above ^^

**Comment by Platonn** [comment]
QA steps in the comment above ^^
